# Generated by Django 4.0.1 on 2022-06-30 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('balances', models.JSONField(null=True)),
                ('mask', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('official_name', models.CharField(max_length=100, null=True)),
                ('subtype', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('account_owner', models.CharField(max_length=100, null=True)),
                ('amount', models.FloatField()),
                ('authorized_date', models.DateField(null=True)),
                ('authorized_datetime', models.DateTimeField(null=True)),
                ('category', models.JSONField(null=True)),
                ('category_id', models.CharField(max_length=100, null=True)),
                ('check_number', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(null=True)),
                ('datetime', models.DateTimeField(null=True)),
                ('iso_currency_code', models.CharField(max_length=10, null=True)),
                ('location', models.JSONField(null=True)),
                ('merchant_name', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('payment_channel', models.CharField(max_length=100, null=True)),
                ('payment_meta', models.JSONField(null=True)),
                ('pending', models.CharField(max_length=10, null=True)),
                ('pending_transaction_id', models.CharField(max_length=100, null=True)),
                ('personal_finance_category', models.CharField(max_length=100, null=True)),
                ('transaction_code', models.CharField(max_length=100, null=True)),
                ('transaction_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(max_length=100, null=True)),
                ('unofficial_currency_code', models.CharField(max_length=100, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plaid_app.account')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('access_token', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plaid_app.item'),
        ),
    ]
